import type { Quiz } from '@/types'

export const QUIZZES: Quiz[] = [
  {
    id: 'quiz-cac-basico',
    title: 'CAC — Fundamentos',
    description: 'Teste seus conhecimentos sobre registro CAC e modalidades.',
    isPremium: false,
    timeLimit: 600,
    questions: [
      {
        id: 'q1',
        question: 'Quais são as três modalidades do sistema CAC?',
        options: [
          'Civil, Militar e Policial',
          'Colecionador, Atirador Desportivo e Caçador',
          'Posse, Porte e Comercialização',
          'Defesa, Esporte e Caça',
        ],
        correctIndex: 1,
        explanation:
          'O CAC compreende três modalidades: Colecionador, Atirador Desportivo e Caçador, conforme Art. 6º da Lei 10.826/2003.',
        sourceDocumentId: 'doc-cac',
        sourceReference: 'Lei 10.826/2003, Art. 6º',
        difficulty: 'iniciante',
        category: 'legislacao',
      },
      {
        id: 'q2',
        question: 'O registro CAC é feito junto a qual órgão?',
        options: ['Polícia Federal', 'Exército Brasileiro (SIGMA/SINARM)', 'Polícia Civil', 'Ministério da Justiça'],
        correctIndex: 1,
        explanation: 'O registro de armas CAC é realizado junto ao Exército Brasileiro, por meio do SIGMA/SINARM.',
        sourceDocumentId: 'doc-cac',
        sourceReference: 'Decreto 9.847/2019',
        difficulty: 'iniciante',
        category: 'legislacao',
      },
      {
        id: 'q3',
        question: 'Qual documento comprova aptidão psicológica para CAC?',
        options: [
          'Atestado médico geral',
          'Laudo psicológico específico',
          'Certificado de curso online',
          'Declaração do clube de tiro',
        ],
        correctIndex: 1,
        explanation: 'A aptidão psicológica deve ser comprovada por laudo psicológico específico, conforme requisitos do Exército.',
        sourceDocumentId: 'doc-cac',
        sourceReference: 'Decreto 9.847/2019',
        difficulty: 'intermediario',
        category: 'legislacao',
      },
    ],
  },
  {
    id: 'quiz-posse-porte',
    title: 'Posse vs Porte',
    description: 'Entenda as diferenças entre posse e porte de armas.',
    isPremium: false,
    timeLimit: 480,
    questions: [
      {
        id: 'q4',
        question: 'O que caracteriza a POSSE de arma de fogo?',
        options: [
          'Direito de transitar com a arma',
          'Direito de manter a arma em residência ou local autorizado',
          'Direito de vender armas',
          'Direito de fabricar munições',
        ],
        correctIndex: 1,
        explanation: 'Posse é o direito de manter a arma em residência ou local de guarda autorizado (Art. 3º, Decreto 9.847/2019).',
        sourceDocumentId: 'doc-posse',
        sourceReference: 'Decreto 9.847/2019, Art. 3º',
        difficulty: 'iniciante',
        category: 'legislacao',
      },
      {
        id: 'q5',
        question: 'O porte de trânsito CAC permite:',
        options: [
          'Carregar a arma em qualquer lugar',
          'Transportar entre residência e local de prática',
          'Vender armas em feiras',
          'Portar arma municiada no carro',
        ],
        correctIndex: 1,
        explanation: 'O porte de trânsito permite transporte entre residência e local de prática (clube, área de caça).',
        sourceDocumentId: 'doc-porte',
        sourceReference: 'Portaria COLOG nº 118/2017, Art. 12',
        difficulty: 'intermediario',
        category: 'normas',
      },
    ],
  },
  {
    id: 'quiz-seguranca',
    title: 'Segurança com Armas',
    description: 'Regras fundamentais de segurança — simulado avançado.',
    isPremium: true,
    timeLimit: 300,
    questions: [
      {
        id: 'q6',
        question: 'Ao transportar uma arma, ela deve estar:',
        options: [
          'Municiada no coldre',
          'Descarregada, em estojo, munição separada',
          'Carregada no porta-luvas',
          'Sob o banco do motorista',
        ],
        correctIndex: 1,
        explanation: 'Transporte exige arma descarregada, em estojo/case rígido, com municionamento separado.',
        sourceDocumentId: 'doc-transporte',
        sourceReference: 'Manual de Segurança, Seção 3.2',
        difficulty: 'iniciante',
        category: 'seguranca',
      },
      {
        id: 'q7',
        question: 'Qual a primeira regra de segurança com armas?',
        options: [
          'Sempre atirar primeiro',
          'Tratar toda arma como se estivesse carregada',
          'Guardar munição junto com a arma',
          'Compartilhar armas com amigos',
        ],
        correctIndex: 1,
        explanation: 'A regra #1 de segurança: tratar TODA arma como se estivesse carregada.',
        sourceDocumentId: 'doc-seguranca',
        sourceReference: 'Normas de Segurança, Regra 1',
        difficulty: 'iniciante',
        category: 'seguranca',
      },
    ],
  },
]

export const LEADERBOARD = [
  { rank: 1, name: 'Carlos M.', score: 98, badge: '🏆' },
  { rank: 2, name: 'Ana P.', score: 95, badge: '🥈' },
  { rank: 3, name: 'Roberto S.', score: 92, badge: '🥉' },
  { rank: 4, name: 'Você', score: 85, badge: '⭐' },
  { rank: 5, name: 'Fernanda L.', score: 82, badge: '' },
]
